### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by NikoPushkin** [11me/nbac#1]
- [x] Decompose base refactoring steps.

Base refactoring steps:
- [x] move database init to specific place;
- [x] database connection;
- [ ] database query execution

Etc

**Comment by NikoPushkin** [comment]
Include database connection init to SQLiteSession class
Move DB initialization to main.ts
use c SQLiteSession instance methods within views

add execute and query methods to SQLiteSession class to make transactions

**Comment by 11me** [comment]
@NikoPushkin 
rename [changeNotifications](https://github.com/11me/nbac/blob/f18402fcf075cd3f16690322507f5bf55806827f/src/views/SourcePage.vue#L31) to toggleNotificationState
